apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mvp-test-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mvp-test-component
    app.kubernetes.io/part-of: mvp-test-app
  name: mvp-test-component
  namespace: mvp-demo-dev-namespace-zgta-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mvp-test-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mvp-test-component
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:570ba452f83b3ef8bec1dc7bfc642f02ed14e09c807aa0b40cea12fa19e6b531
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
